module.exports = [
  {
    "id": 1,
    "ratings": 2,
    "title": "Very small for $6",
    "description": "This is why you should check measurements before buying. My mistake. It’s rrakky small. Fits in palm of my hand. It’s soft & cute but too small for $6 in my opinion.",
    "productId": 1,
    "userId": 1,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2001-06-06 20:57:09"
  },
  {
    "id": 2,
    "ratings": 3,
    "title": "Doloremque quam ratione iste assumenda rerum voluptas voluptatem.",
    "description": "Sit ipsam pariatur corrupti ut dolore laudantium eligendi. Omnis doloribus sit culpa et corrupti. Quibusdam dolorem est distinctio libero quibusdam sint necessitatibus.",
    "productId": 2,
    "userId": 2,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1984-12-28 20:51:25"
  },
  {
    "id": 3,
    "ratings": 3,
    "title": "Est impedit ut eligendi ullam reprehenderit officia.",
    "description": "Odit dignissimos quo commodi nemo eveniet voluptatem libero. Quia nihil sint ex ipsa vel deserunt. Molestiae nisi nemo ex ut mollitia ad nobis est.",
    "productId": 3,
    "userId": 3,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1975-09-24 01:28:37"
  },
  {
    "id": 4,
    "ratings": 5,
    "title": "Quibusdam nisi iusto aut necessitatibus nobis molestiae fuga architecto.",
    "description": "Ut in harum rem ut consequatur quibusdam. Harum dolore quis occaecati vero quam qui. Voluptas amet possimus sunt dolorem consectetur. Ut eos harum delectus sed molestiae facilis molestiae. Laborum tempora qui dolorem asperiores quam iste.",
    "productId": 4,
    "userId": 4,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1980-07-16 15:07:53"
  },
  {
    "id": 5,
    "ratings": 2,
    "title": "Iure nisi consequatur provident ea maiores adipisci.",
    "description": "Ratione fugit nihil qui. Dolorem et et eius voluptatem accusantium. Nihil et laborum ut sit voluptatem placeat. Sint quia cupiditate doloremque doloremque facere. Fugiat beatae cumque pariatur quos suscipit sequi.",
    "productId": 5,
    "userId": 5,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2006-02-27 20:54:37"
  },
  {
    "id": 6,
    "ratings": 3,
    "title": "Sint vel minus possimus deleniti ratione velit.",
    "description": "Vero voluptatem vel officiis repellendus corrupti numquam. Nesciunt eum et dolores debitis amet ut.",
    "productId": 6,
    "userId": 6,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1971-06-16 01:10:15"
  },
  {
    "id": 7,
    "ratings": 2,
    "title": "Occaecati deserunt nam voluptatem eveniet similique vitae qui.",
    "description": "Assumenda iusto id consequatur rerum assumenda maiores culpa. Cum dolores inventore nobis laborum voluptatum. Qui quo quae quia sit. Nam ea voluptatem aliquam voluptas qui illum.",
    "productId": 7,
    "userId": 7,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2001-07-15 23:04:07"
  },
  {
    "id": 8,
    "ratings": 3,
    "title": "Aut iste earum iste exercitationem voluptate.",
    "description": "Provident accusamus repellat ab pariatur. Facilis ut architecto quae. Accusantium voluptatem nobis corporis. Eveniet vero ut quis.",
    "productId": 8,
    "userId": 8,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2014-04-08 08:02:10"
  },
  {
    "id": 9,
    "ratings": 3,
    "title": "Sequi ipsum itaque quo voluptas neque delectus quibusdam.",
    "description": "Repellat quod quia quia ratione ea amet. Ut unde dolores quia incidunt qui aspernatur id. Sed error sed autem distinctio. Omnis cupiditate fugiat magnam explicabo sunt.",
    "productId": 9,
    "userId": 9,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1987-01-19 08:26:11"
  },
  {
    "id": 10,
    "ratings": 1,
    "title": "Praesentium expedita nobis tenetur.",
    "description": "Asperiores perspiciatis cum iure earum id est et quas. Quibusdam error corporis architecto quisquam. Ipsa doloremque a eum ullam quis deserunt aut.",
    "productId": 10,
    "userId": 10,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1975-09-13 15:13:31"
  },
  {
    "id": 11,
    "ratings": 4,
    "title": "Great Plush!",
    "description": "It's cute and it's soft to the touch. I gave it to someone as a present and they love it very much. My biggest issue with it is that it's more like a 6' Plush than an 8' Plush. It's considerably smaller than I really expected given the image on Amazon. I was expecting it to by 8' in the sitting position, not 8' when it's stretched out.",
    "productId": 1,
    "userId": 11,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2018-10-29 08:11:56"
  },
  {
    "id": 12,
    "ratings": 1,
    "title": "Aut mollitia veniam dolorem nam corporis.",
    "description": "Et facere ipsum qui ipsum. Odit quis dicta odit accusantium. Ab earum optio harum aliquam rem nesciunt.",
    "productId": 2,
    "userId": 12,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2002-01-10 21:36:43"
  },
  {
    "id": 13,
    "ratings": 1,
    "title": "Possimus corrupti qui modi quos debitis quia vero.",
    "description": "Est dolorum et ut quasi id sed at odio. Esse aut vero et voluptatem nam iusto tenetur. Sed quia perspiciatis sint porro. Tempora et omnis assumenda autem consequuntur maiores qui.",
    "productId": 3,
    "userId": 13,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2002-09-03 11:27:29"
  },
  {
    "id": 14,
    "ratings": 1,
    "title": "Numquam unde qui distinctio sint animi enim aut.",
    "description": "Et quae nostrum quibusdam quod sed quis a et. Doloremque ducimus non architecto et est voluptas dolorum. Voluptas cumque cumque sequi ea ex quis rerum.",
    "productId": 4,
    "userId": 14,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1984-03-30 08:51:22"
  },
  {
    "id": 15,
    "ratings": 5,
    "title": "Ea tempora recusandae corrupti laudantium officiis cum earum.",
    "description": "Architecto at totam consequatur nihil. Voluptatem similique et quos dolor. Ipsam sint quia explicabo in quia ullam omnis. Et aperiam voluptatem voluptatem harum corporis.",
    "productId": 5,
    "userId": 15,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1995-02-17 23:06:46"
  },
  {
    "id": 16,
    "ratings": 4,
    "title": "Tenetur nobis optio quo doloremque porro rem est sit.",
    "description": "Magni minima unde rem harum deleniti culpa aut assumenda. Quia sed commodi dolore at magni. Consectetur molestiae recusandae atque minima recusandae enim. Consequatur quia quas sint.",
    "productId": 6,
    "userId": 16,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1998-03-25 09:33:18"
  },
  {
    "id": 17,
    "ratings": 4,
    "title": "Excepturi dolore nulla cum aut qui rerum rerum.",
    "description": "Ut rerum totam vel voluptatem eum ipsa dolores provident. Et voluptatem est ea pariatur deserunt. Quidem eos aut suscipit repellendus.",
    "productId": 7,
    "userId": 17,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1991-10-20 08:03:59"
  },
  {
    "id": 18,
    "ratings": 5,
    "title": "Tenetur adipisci iure nobis reprehenderit sunt odit animi ipsa.",
    "description": "Soluta veritatis sint consectetur perspiciatis. Officia sit consectetur hic in. Sed occaecati voluptatibus ab dolores.",
    "productId": 8,
    "userId": 18,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1973-07-28 09:28:15"
  },
  {
    "id": 19,
    "ratings": 1,
    "title": "Veritatis quibusdam ex quas debitis ab.",
    "description": "Ipsum quis sint id ipsum dolor sunt occaecati. Accusamus inventore id ut qui. Aliquam ut dolor est esse possimus doloribus sapiente. Est dolorem iure reiciendis.",
    "productId": 9,
    "userId": 19,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1999-05-16 22:05:50"
  },
  {
    "id": 20,
    "ratings": 5,
    "title": "Dicta ut nostrum et.",
    "description": "Sunt est in aut enim occaecati sapiente dolores. Amet dolor at iste. Molestiae quisquam explicabo assumenda sunt temporibus excepturi. Qui blanditiis ullam repellat ducimus minus.",
    "productId": 10,
    "userId": 20,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2001-08-18 03:42:25"
  },
  {
    "id": 21,
    "ratings": 3,
    "title": "Soft and cuddly",
    "description": "Ordered this product for my child’s school counselor to be used in conjunction with social emotional learning book. Her counselor loved it and so do the kids.",
    "productId": 1,
    "userId": 21,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1991-04-14 12:02:18"
  },
  {
    "id": 22,
    "ratings": 3,
    "title": "Qui quis expedita voluptates facere incidunt culpa.",
    "description": "Sit expedita ad delectus delectus suscipit nemo qui. Necessitatibus animi autem earum voluptatem. Et hic ducimus maxime ex est molestiae ratione possimus. Alias impedit similique omnis dolor.",
    "productId": 2,
    "userId": 22,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1998-10-19 13:03:08"
  },
  {
    "id": 23,
    "ratings": 2,
    "title": "Impedit explicabo voluptatem culpa.",
    "description": "Molestias a quae rerum consequatur voluptas qui. Quo dolore est aut ipsum. Saepe ratione dolore laborum officiis.",
    "productId": 3,
    "userId": 23,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2015-01-13 00:49:22"
  },
  {
    "id": 24,
    "ratings": 3,
    "title": "Quasi quo corrupti repellendus corrupti.",
    "description": "Vel laborum sed id. Odio non veniam non. Iure commodi ut incidunt.",
    "productId": 4,
    "userId": 24,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2004-03-05 11:12:01"
  },
  {
    "id": 25,
    "ratings": 5,
    "title": "Magnam atque quam placeat sed illum.",
    "description": "Nam dolores enim accusamus neque autem nihil. Minus id reprehenderit est deleniti quae unde quam.",
    "productId": 5,
    "userId": 25,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1979-09-05 00:17:02"
  },
  {
    "id": 26,
    "ratings": 2,
    "title": "Iste consequatur architecto laboriosam voluptate aut vitae.",
    "description": "Odio corrupti optio et voluptatem harum. Non ducimus accusamus magni doloremque odio dolorum. Laborum et labore illum provident ipsam dolorem et.",
    "productId": 6,
    "userId": 26,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2003-05-25 11:48:34"
  },
  {
    "id": 27,
    "ratings": 2,
    "title": "Quae laborum odio non.",
    "description": "Sunt sapiente aperiam exercitationem quo. Est et similique ipsa labore suscipit. Molestiae qui culpa illum dolorem iusto natus. Consequatur fugit est ex ad.",
    "productId": 7,
    "userId": 27,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1982-04-28 02:35:31"
  },
  {
    "id": 28,
    "ratings": 3,
    "title": "Assumenda est quia sed.",
    "description": "Incidunt et voluptates facere ut aut nulla quo. Delectus numquam nesciunt eaque voluptatibus. Quisquam eum et nihil eum porro.",
    "productId": 8,
    "userId": 28,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2019-01-24 09:24:32"
  },
  {
    "id": 29,
    "ratings": 1,
    "title": "Ullam eos eum ad sed.",
    "description": "Dolor et voluptatem aut amet cupiditate corporis quod. Quidem impedit voluptas error fugiat voluptas voluptatibus eius. Tempora eligendi rerum voluptate asperiores.",
    "productId": 9,
    "userId": 29,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2000-05-13 13:08:42"
  },
  {
    "id": 30,
    "ratings": 2,
    "title": "Excepturi vel earum molestiae est ipsa officia.",
    "description": "Quia omnis voluptatem molestiae accusantium voluptatem soluta. Et sequi odio voluptas vel amet. Excepturi doloremque minima quasi enim. Consequatur laborum neque et commodi cum consequatur vero ipsum.",
    "productId": 10,
    "userId": 30,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1974-05-30 14:18:36"
  },
  {
    "id": 31,
    "ratings": 1,
    "title": "baby mode",
    "description": "Very lovely..........polite..........shaped like a friend..........",
    "productId": 1,
    "userId": 31,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1972-12-02 01:21:39"
  },
  {
    "id": 32,
    "ratings": 3,
    "title": "Praesentium odit illo et tempora iusto molestias aut numquam.",
    "description": "Corporis magni a et aut omnis quos. Possimus dignissimos consequuntur sunt earum voluptas voluptas. In dolore dolores sed facilis.",
    "productId": 2,
    "userId": 32,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2007-06-25 10:37:41"
  },
  {
    "id": 33,
    "ratings": 3,
    "title": "Hic modi accusamus unde consectetur rerum eos iusto.",
    "description": "Nisi omnis culpa et porro quis et. Odio cumque nihil et ut repellendus. Non error eaque earum.",
    "productId": 3,
    "userId": 33,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2002-10-31 03:06:43"
  },
  {
    "id": 34,
    "ratings": 5,
    "title": "Reiciendis natus eos quidem suscipit.",
    "description": "Excepturi placeat sint voluptas cupiditate. Quis ut voluptatem totam occaecati. Velit consequatur molestiae deleniti blanditiis adipisci reprehenderit enim.",
    "productId": 4,
    "userId": 34,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1972-10-21 17:41:38"
  },
  {
    "id": 35,
    "ratings": 5,
    "title": "Quod quibusdam qui suscipit reiciendis ipsum temporibus distinctio.",
    "description": "Magnam nobis modi vel nulla ipsum eum doloribus. Rerum ipsa voluptas qui quia ut alias consequatur nobis. Nihil dolores quod eaque tenetur.",
    "productId": 5,
    "userId": 35,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2019-01-06 21:48:31"
  },
  {
    "id": 36,
    "ratings": 1,
    "title": "Recusandae et maxime est delectus nostrum repudiandae eaque.",
    "description": "Omnis sint voluptas quos vel repellat. Natus neque libero labore aut. Dolorum consequuntur at nemo dolorum repudiandae. Mollitia quia eaque deserunt.",
    "productId": 6,
    "userId": 36,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1989-12-15 06:01:47"
  },
  {
    "id": 37,
    "ratings": 4,
    "title": "Sit beatae impedit ipsum aut ut vel.",
    "description": "Quos aut vitae voluptas nemo. Hic maxime excepturi qui quod rem possimus sunt. Quo nam consequatur repudiandae similique non quia nam. Quia sed distinctio unde totam nihil in quia quam. Placeat distinctio quidem quia rerum tenetur.",
    "productId": 7,
    "userId": 37,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2008-02-06 19:43:41"
  },
  {
    "id": 38,
    "ratings": 1,
    "title": "Magnam dignissimos fugiat in ut et explicabo.",
    "description": "Aliquid et sint ducimus quia quis nihil. Quidem recusandae reprehenderit nihil eligendi aut. Reprehenderit voluptatem officia voluptas molestiae et veritatis. Optio consequatur officiis rerum dicta qui saepe.",
    "productId": 8,
    "userId": 38,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2007-12-29 01:34:06"
  },
  {
    "id": 39,
    "ratings": 4,
    "title": "Consequatur omnis quia ipsum aperiam quos reiciendis quam officia.",
    "description": "Assumenda sunt repellat illum illo ipsa nostrum. Doloremque minima ratione impedit ea. Animi hic cumque beatae doloribus vel ad occaecati harum. Hic non nihil sit labore neque accusantium quas.",
    "productId": 9,
    "userId": 39,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1999-07-04 14:47:08"
  },
  {
    "id": 40,
    "ratings": 1,
    "title": "Libero quo doloribus eos et sunt dignissimos.",
    "description": "Adipisci aliquam porro recusandae. Et reprehenderit qui in iure. Sit quisquam deserunt aut facilis modi unde autem. Qui neque ut voluptatem adipisci exercitationem sed.",
    "productId": 10,
    "userId": 40,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1990-01-29 16:08:21"
  },
  {
    "id": 41,
    "ratings": 3,
    "title": "Aut officia repudiandae cupiditate illo reprehenderit modi nulla.",
    "description": "Unde ut et occaecati. Aut qui tempora libero. Praesentium unde temporibus maiores voluptatum voluptatem quo. Voluptatem qui eos ut omnis porro omnis pariatur. Unde ut et occaecati. Aut qui tempora libero. Praesentium unde temporibus maiores voluptatum voluptatem quo. Voluptatem qui eos ut omnis porro omnis pariatur.Doloremque ea quibusdam magni beatae facilis voluptatem error. Sint mollitia dolor officiis neque. In repudiandae asperiores eum consequatur ut maxime. Assumenda nihil fugiat consequatur inventore.Doloremque ea quibusdam magni beatae facilis voluptatem error. Sint mollitia dolor officiis neque. In repudiandae asperiores eum consequatur ut maxime. Assumenda nihil fugiat consequatur inventore.Doloremque ea quibusdam magni beatae facilis voluptatem error. Sint mollitia dolor officiis neque. In repudiandae asperiores eum consequatur ut maxime. Assumenda nihil fugiat consequatur inventore. ",
    "productId": 1,
    "userId": 41,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1987-07-27 01:17:25"
  },
  {
    "id": 42,
    "ratings": 2,
    "title": "Alias nesciunt repellendus velit.",
    "description": "Doloremque ea quibusdam magni beatae facilis voluptatem error. Sint mollitia dolor officiis neque. In repudiandae asperiores eum consequatur ut maxime. Assumenda nihil fugiat consequatur inventore.",
    "productId": 2,
    "userId": 42,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2013-04-17 14:44:46"
  },
  {
    "id": 43,
    "ratings": 3,
    "title": "In autem animi omnis accusantium distinctio sed.",
    "description": "Quos dolore quibusdam beatae vitae voluptate maiores error. Aut sunt nam et omnis illum dolor. Dolores consequatur qui non enim enim minus quisquam.",
    "productId": 3,
    "userId": 43,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1983-05-24 19:43:08"
  },
  {
    "id": 44,
    "ratings": 4,
    "title": "Quis quia cumque maiores perspiciatis est optio.",
    "description": "Ex maiores enim distinctio assumenda ex. Voluptatum omnis aut error iure. Earum laboriosam exercitationem voluptatem dolore vel deleniti sequi magni.",
    "productId": 4,
    "userId": 44,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2002-08-21 20:36:32"
  },
  {
    "id": 45,
    "ratings": 2,
    "title": "Labore ut et consequatur non placeat nihil.",
    "description": "Velit perspiciatis sit ipsam recusandae ea minus sed. Iusto aut aut nemo ut. Et voluptatibus doloribus rerum corporis est impedit.",
    "productId": 5,
    "userId": 45,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1982-01-31 17:33:09"
  },
  {
    "id": 46,
    "ratings": 4,
    "title": "Ut quas illum eos nostrum incidunt sint sed amet.",
    "description": "Aliquid fugit qui neque dolor ut iure. Occaecati atque quas animi omnis. Quisquam et at aut veniam. Facere ea nesciunt sint. Explicabo nihil minus velit magnam rerum tempora qui.",
    "productId": 6,
    "userId": 46,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1970-08-21 01:34:08"
  },
  {
    "id": 47,
    "ratings": 3,
    "title": "Sit distinctio nihil alias dolor aut distinctio maxime.",
    "description": "Voluptate sint enim veritatis magni qui. Fugit nemo non tempore iure commodi animi. Totam voluptates repellendus corporis earum labore. Nam voluptates omnis aliquid. Repellat amet consequatur doloribus molestias alias ut eos est.",
    "productId": 7,
    "userId": 47,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2004-06-01 13:35:01"
  },
  {
    "id": 48,
    "ratings": 3,
    "title": "Et nemo iusto eius.",
    "description": "Harum illum aliquid consectetur laudantium earum soluta. Quae sed voluptatibus minima et et iste aut alias. Officiis est placeat temporibus repellendus. Est reprehenderit sunt quos sit laborum quia.",
    "productId": 8,
    "userId": 48,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1979-08-23 01:05:52"
  },
  {
    "id": 49,
    "ratings": 1,
    "title": "Voluptatem voluptas qui officiis illo laudantium enim odit.",
    "description": "Quia porro dignissimos nulla. Porro sunt numquam iure dolorum. Voluptate totam est quis rem ipsa.",
    "productId": 9,
    "userId": 49,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1995-01-27 09:42:29"
  },
  {
    "id": 50,
    "ratings": 5,
    "title": "Et nam laborum voluptas voluptatibus dolore fugit porro in.",
    "description": "Nulla quibusdam ad ex in repellat doloremque sit. Atque dolor voluptatem aut. Dolores dolorem numquam quod laborum facere consequatur ut.",
    "productId": 10,
    "userId": 50,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2014-03-09 19:35:03"
  },
  {
    "id": 51,
    "ratings": 4,
    "title": "Quo enim in mollitia sed eos.",
    "description": "Et voluptatem ducimus autem architecto et unde. Ea ratione eius aut aut cum dolorum quia. Ex consequatur molestiae rerum voluptatum quo reprehenderit. Minus nam et consequatur commodi itaque libero.",
    "productId": 1,
    "userId": 51,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2000-03-03 10:40:09"
  },
  {
    "id": 52,
    "ratings": 5,
    "title": "Tempora repellat occaecati sint eaque ea in.",
    "description": "Quis at corporis ipsam rerum totam consectetur rem libero. Eum velit quisquam est qui voluptatem commodi. Adipisci et architecto non autem consequatur ex. Aut est deleniti nam eum veritatis.",
    "productId": 2,
    "userId": 52,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2013-10-17 01:35:39"
  },
  {
    "id": 53,
    "ratings": 1,
    "title": "Distinctio totam amet quia possimus tenetur.",
    "description": "Qui enim animi aut. Totam sint aut eum recusandae. Voluptatem explicabo omnis nihil voluptatem ipsa architecto facere sed.",
    "productId": 3,
    "userId": 53,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2004-05-28 11:37:04"
  },
  {
    "id": 54,
    "ratings": 2,
    "title": "Delectus hic dolorem quam enim doloremque enim tempora.",
    "description": "Tempore sit inventore voluptatibus nesciunt. Aut id aut saepe dolorem voluptatum est. Dolore rerum blanditiis quo quidem a id dolor officia.",
    "productId": 4,
    "userId": 54,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1971-03-18 09:25:14"
  },
  {
    "id": 55,
    "ratings": 1,
    "title": "Vel tempore qui est neque fuga.",
    "description": "Tempora rerum placeat numquam quasi et qui. Quos quia neque optio illum corrupti harum sit reprehenderit. Perferendis quod temporibus totam nesciunt qui tenetur. Voluptatem rerum voluptatem quidem doloribus atque consequatur ex.",
    "productId": 5,
    "userId": 55,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1983-08-31 08:35:37"
  },
  {
    "id": 56,
    "ratings": 2,
    "title": "Impedit nostrum fugit similique sunt soluta cumque adipisci.",
    "description": "Illum quia quod eos est unde doloremque ut. Rerum sint doloribus enim animi sed. Sequi illum exercitationem dolores exercitationem sed. Est et repellendus vel odio blanditiis.",
    "productId": 6,
    "userId": 56,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1986-07-01 14:12:21"
  },
  {
    "id": 57,
    "ratings": 3,
    "title": "Exercitationem et repellat cum dicta vel quo et ut.",
    "description": "Ut quas sed deserunt sed. Omnis voluptatem minus dolorum vitae autem unde accusantium. Quidem dignissimos quia illo.",
    "productId": 7,
    "userId": 57,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1983-02-24 23:28:36"
  },
  {
    "id": 58,
    "ratings": 5,
    "title": "Quas officiis illo aperiam.",
    "description": "Recusandae vitae aut sunt molestias aut eos error. Accusamus nam magni non quae aperiam dignissimos architecto eveniet. Eveniet modi sint debitis consequatur ea quia. Aut eaque nisi quia iusto qui.",
    "productId": 8,
    "userId": 58,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2018-09-20 22:56:03"
  },
  {
    "id": 59,
    "ratings": 1,
    "title": "Et quidem voluptatum ut et laboriosam est tenetur.",
    "description": "Vel possimus voluptas dolorem sunt eum. Dignissimos ea assumenda voluptatum provident sint. Eveniet officiis tempore rem hic totam rerum. Aperiam earum ut nam aut doloremque reprehenderit ad. Suscipit et quas iusto minus dolorem voluptatum.",
    "productId": 9,
    "userId": 59,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1976-11-27 14:58:08"
  },
  {
    "id": 60,
    "ratings": 3,
    "title": "Quis maiores nostrum mollitia nihil necessitatibus impedit.",
    "description": "Et consectetur itaque expedita repellat laboriosam consequatur quo. Nemo temporibus modi eius quo. Voluptatem maxime quia qui eaque et molestiae.",
    "productId": 10,
    "userId": 60,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1988-12-04 09:19:02"
  },
  {
    "id": 61,
    "ratings": 5,
    "title": "Absolutely Perfect",
    "description": "Super soft,cute and completely perfect to add the finishing touches to my Granddaughter's Halloween costume.",
    "productId": 1,
    "userId": 61,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2001-09-14 02:17:06"
  },
  {
    "id": 62,
    "ratings": 3,
    "title": "Voluptatem cupiditate ratione odit rerum ipsam fuga.",
    "description": "Ad corrupti iste ut deserunt deleniti. Deserunt aperiam consequatur provident veritatis. Non dolorem vero ad repellat nostrum sed. Et illum et quas eum nihil nam ut.",
    "productId": 2,
    "userId": 62,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1979-08-02 06:55:38"
  },
  {
    "id": 63,
    "ratings": 5,
    "title": "Sed deleniti deleniti est itaque quia corrupti.",
    "description": "Tempore modi corporis vel eum et quo velit. Qui iure doloremque numquam cum. Occaecati quod ea beatae assumenda est maiores.",
    "productId": 3,
    "userId": 63,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1972-06-02 21:55:17"
  },
  {
    "id": 64,
    "ratings": 3,
    "title": "Dicta maiores rerum debitis voluptatum et ut.",
    "description": "Est accusantium ut nemo veritatis eius. Commodi et ut eaque quod corporis magni. Sequi vel nam laborum tempore rerum ut fugit iste. Suscipit ut qui et eaque cum tenetur.",
    "productId": 4,
    "userId": 64,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2008-11-24 03:54:53"
  },
  {
    "id": 65,
    "ratings": 5,
    "title": "Vel voluptates vel eos quia in eveniet.",
    "description": "Non libero voluptas voluptates cupiditate quasi et. Dolorem incidunt ipsa quia quidem voluptatem eius fugiat expedita. Nesciunt nesciunt reiciendis cumque molestiae voluptate et consequatur. Fugit a illum perspiciatis optio ea.",
    "productId": 5,
    "userId": 65,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1989-09-24 14:59:28"
  },
  {
    "id": 66,
    "ratings": 3,
    "title": "Adipisci repellat velit commodi ea eligendi omnis aut.",
    "description": "Maxime quo quaerat et sequi minima. Blanditiis et placeat fuga vitae quo quis. Id deserunt nemo aliquam id enim. Sed odio itaque harum fugiat eos beatae magni.",
    "productId": 6,
    "userId": 66,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1976-03-10 00:07:15"
  },
  {
    "id": 67,
    "ratings": 4,
    "title": "Vitae deserunt nobis sit quidem.",
    "description": "Magnam quaerat qui aut voluptate temporibus odit est. Tempore aut error dolorem aut doloribus eveniet. Quaerat aut eaque soluta laborum veritatis perferendis quis. Ipsum consequuntur ad dolore illo quia recusandae.",
    "productId": 7,
    "userId": 67,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1977-06-10 13:49:40"
  },
  {
    "id": 68,
    "ratings": 4,
    "title": "Ipsam quis unde voluptatum.",
    "description": "Nisi quia quia eius quis mollitia aut. Natus sapiente et est est eos non. Consequatur eaque quis est soluta optio impedit occaecati.",
    "productId": 8,
    "userId": 68,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1973-04-10 14:00:31"
  },
  {
    "id": 69,
    "ratings": 5,
    "title": "Odit culpa nulla quia et cum harum.",
    "description": "Illo blanditiis perspiciatis illum aspernatur. Ipsam sunt explicabo placeat consequuntur qui. Nesciunt tenetur eum sed placeat et vero.",
    "productId": 9,
    "userId": 69,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1980-10-23 11:47:34"
  },
  {
    "id": 70,
    "ratings": 2,
    "title": "Vero possimus assumenda deserunt ipsam eius ex sunt ullam.",
    "description": "Eligendi accusamus sunt excepturi eum laborum odio aut. Facilis labore temporibus dignissimos corrupti.",
    "productId": 10,
    "userId": 70,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2010-02-12 11:19:39"
  },
  {
    "id": 71,
    "ratings": 3,
    "title": "Hic unde aliquid modi qui.",
    "description": "Voluptas nulla ut provident magnam quis fugiat. Sequi nulla cumque non numquam veniam dignissimos voluptatem tempore. Neque et atque neque voluptas atque porro est. Similique aperiam inventore beatae quia blanditiis dolores.",
    "productId": 1,
    "userId": 71,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1983-01-06 04:13:06"
  },
  {
    "id": 72,
    "ratings": 1,
    "title": "Voluptatem rerum reprehenderit autem temporibus quidem modi voluptatibus.",
    "description": "Ipsa sit id error blanditiis similique assumenda ad. Nesciunt quo dignissimos corporis tempora. Et placeat quam quas facilis sint. Est consectetur aperiam modi et voluptas ad ex.",
    "productId": 2,
    "userId": 72,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2013-09-07 05:55:50"
  },
  {
    "id": 73,
    "ratings": 5,
    "title": "Natus numquam totam voluptas ut officia ducimus.",
    "description": "Autem dolorum est commodi cum et. Culpa reiciendis qui iure eveniet reiciendis et cupiditate. Unde blanditiis commodi tempore nulla et asperiores ut. Illo dolorem quam quia excepturi. In aut architecto placeat occaecati.",
    "productId": 3,
    "userId": 73,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2015-05-17 07:30:48"
  },
  {
    "id": 74,
    "ratings": 4,
    "title": "Nisi distinctio amet et voluptatum et quia perspiciatis.",
    "description": "Quis amet aperiam aut perferendis tenetur voluptates quae. Saepe eum atque quidem ut atque. Ipsa hic atque dolores est officiis beatae. Occaecati nihil quam et.",
    "productId": 4,
    "userId": 74,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1986-06-16 00:58:00"
  },
  {
    "id": 75,
    "ratings": 5,
    "title": "Consequuntur consequatur molestias quidem consequatur accusantium et.",
    "description": "Adipisci culpa impedit eum animi. Quaerat repellendus aliquid odit quaerat culpa voluptatum voluptatem. Aut sunt rerum et voluptatem.",
    "productId": 5,
    "userId": 75,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1983-03-09 10:14:01"
  },
  {
    "id": 76,
    "ratings": 4,
    "title": "Cum aut autem aut vero est sunt porro.",
    "description": "Saepe dignissimos earum beatae quos nihil deserunt. Aut et doloribus est et. Vero qui sequi natus ut repellat. Natus nisi quod voluptatem sed.",
    "productId": 6,
    "userId": 76,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1979-01-22 04:22:48"
  },
  {
    "id": 77,
    "ratings": 2,
    "title": "Ut dolore qui ea vitae nemo est est.",
    "description": "Distinctio culpa enim quia eos quam. Eveniet enim amet suscipit vel. Officiis voluptatum tempora quae.",
    "productId": 7,
    "userId": 77,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1985-09-30 18:45:03"
  },
  {
    "id": 78,
    "ratings": 1,
    "title": "Placeat voluptatem vel cum omnis ullam magnam qui.",
    "description": "Ipsam sequi earum fuga dolores dolor sint autem. Et rerum omnis quia distinctio accusantium et. Tempore expedita quis consequatur eos. Temporibus sit amet minus ut eligendi maxime iure.",
    "productId": 8,
    "userId": 78,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1977-01-26 21:00:56"
  },
  {
    "id": 79,
    "ratings": 3,
    "title": "Libero nisi omnis dolore nulla et voluptatem voluptas cum.",
    "description": "Aperiam incidunt quaerat suscipit aut. Est nam amet iure et aliquid et dolor. Nesciunt ut non rem ea. Sit et totam beatae.",
    "productId": 9,
    "userId": 79,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2005-04-29 12:45:48"
  },
  {
    "id": 80,
    "ratings": 5,
    "title": "At modi occaecati deserunt iste.",
    "description": "Maxime omnis aut asperiores quia error. Deserunt amet eligendi sit et est enim animi. Cum doloremque adipisci perspiciatis possimus assumenda velit in est. Voluptatum dolor ad aspernatur repellendus est atque nesciunt.",
    "productId": 10,
    "userId": 80,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1994-07-05 17:43:12"
  },
  {
    "id": 81,
    "ratings": 3,
    "title": "Omnis tenetur dolor odio quae ipsam aperiam voluptatem.",
    "description": "Et esse eaque eos aliquam possimus aut sit sint. Molestias non iure ullam consectetur.",
    "productId": 1,
    "userId": 81,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1977-05-21 12:49:19"
  },
  {
    "id": 82,
    "ratings": 4,
    "title": "Vitae minima et velit cumque consectetur aut aut blanditiis.",
    "description": "Nesciunt eius neque doloribus molestiae et. Sed repellendus expedita ea est et porro repellat sunt. Sed iure magni veritatis est impedit voluptatibus.",
    "productId": 2,
    "userId": 82,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2018-11-09 19:14:02"
  },
  {
    "id": 83,
    "ratings": 2,
    "title": "Temporibus quibusdam cumque voluptate optio error aperiam corrupti.",
    "description": "Quia et omnis omnis delectus harum sequi. Voluptas illum minus modi tenetur sint voluptates. Dolores sed et dolorem atque.",
    "productId": 3,
    "userId": 83,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1993-05-19 05:57:31"
  },
  {
    "id": 84,
    "ratings": 3,
    "title": "Inventore dignissimos quasi accusamus rem sit non.",
    "description": "Sapiente temporibus numquam tempora modi eos. Et ut sed saepe dolore delectus voluptatum cupiditate. Optio ratione id voluptas vel deleniti. Repellat cumque doloremque similique voluptas pariatur rerum nisi omnis.",
    "productId": 4,
    "userId": 84,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1994-05-13 20:27:50"
  },
  {
    "id": 85,
    "ratings": 5,
    "title": "Repellendus magnam sit autem ab aut.",
    "description": "Quae recusandae temporibus magni non libero. Omnis autem accusamus voluptatum rem possimus eos eaque nihil. Sed praesentium voluptatum ut eos hic.",
    "productId": 5,
    "userId": 85,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "1996-07-19 15:42:26"
  },
  {
    "id": 86,
    "ratings": 2,
    "title": "Repellendus qui atque est vel beatae sint.",
    "description": "Quia nihil in in ratione et. Excepturi et hic qui molestiae doloribus.",
    "productId": 6,
    "userId": 86,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1997-09-24 00:13:29"
  },
  {
    "id": 87,
    "ratings": 1,
    "title": "Debitis consequuntur sit facilis asperiores non sit alias et.",
    "description": "Distinctio aperiam dolorem tenetur ea consequatur. Sint deserunt dicta ut aut distinctio quisquam aut. Distinctio illo delectus suscipit expedita commodi ex non aut. Delectus sed veritatis saepe ab.",
    "productId": 7,
    "userId": 87,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "1990-05-14 13:01:32"
  },
  {
    "id": 88,
    "ratings": 4,
    "title": "Omnis tempora ut sit et quis id quo.",
    "description": "Maiores corrupti doloribus consectetur ea incidunt in nisi. Sed beatae ad accusantium tenetur. Dolor nihil pariatur rerum ipsam perferendis sit.",
    "productId": 8,
    "userId": 88,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1991-11-09 19:00:32"
  },
  {
    "id": 89,
    "ratings": 3,
    "title": "Magnam officia quia autem enim sunt optio.",
    "description": "Nam est hic tempora molestiae minima. Aliquid id tenetur nisi et occaecati non explicabo cum. Nihil minima odio consequatur sunt.",
    "productId": 9,
    "userId": 89,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "1999-07-29 07:56:23"
  },
  {
    "id": 90,
    "ratings": 5,
    "title": "Quae qui fugit et voluptatibus maxime tempore eos.",
    "description": "Alias modi eum magni excepturi officia culpa. At doloremque voluptas laudantium sit tempora facilis dolor corporis. Corrupti consectetur sunt tempore voluptatem quam. Esse non ut ipsam sit vero dolor ipsa.",
    "productId": 10,
    "userId": 90,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2010-04-09 09:10:03"
  },
  {
    "id": 91,
    "ratings": 4,
    "title": "Rem expedita impedit est atque qui ut quo.",
    "description": "Tempora impedit magni quidem nihil ex rerum. Nobis molestiae ut reiciendis quia. Eos corporis dicta recusandae aliquam et. Facere molestiae commodi totam qui velit eum cupiditate.",
    "productId": 1,
    "userId": 91,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2003-01-27 10:10:05"
  },
  {
    "id": 92,
    "ratings": 4,
    "title": "Quia totam eaque itaque non autem aliquid illum.",
    "description": "Quis eos incidunt recusandae impedit recusandae aut sunt doloremque. Autem aut voluptatum deleniti et aut. Esse ut tempora quia assumenda dicta deleniti a. Itaque omnis sapiente iure amet dolore autem omnis.",
    "productId": 2,
    "userId": 92,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 0,
    "createdOn": "2001-09-21 18:17:11"
  },
  {
    "id": 93,
    "ratings": 2,
    "title": "Repudiandae est eum cumque harum soluta soluta quas.",
    "description": "Consequuntur autem iure cupiditate molestiae temporibus. Doloremque molestiae voluptatem et dolor reiciendis illum. Provident incidunt culpa assumenda tempore ad.",
    "productId": 3,
    "userId": 93,
    "report_abuse": 1,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1971-10-25 15:23:55"
  },
  {
    "id": 94,
    "ratings": 4,
    "title": "Ut dolorem aliquid necessitatibus mollitia.",
    "description": "Veritatis et est error iusto dicta. Et ut iusto excepturi voluptatum. Recusandae aliquam voluptas omnis sed iste consequatur. Enim rerum eum maxime expedita.",
    "productId": 4,
    "userId": 94,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2001-02-20 16:09:46"
  },
  {
    "id": 95,
    "ratings": 1,
    "title": "Autem est voluptas dolorum optio nihil eum.",
    "description": "Blanditiis sunt labore autem sunt fuga aut. Consequuntur sit atque facilis ut neque alias illo. Commodi rem similique mollitia fugit est animi autem. Officiis amet blanditiis et maiores quod sit.",
    "productId": 5,
    "userId": 95,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 1,
    "isProductProp3Good": 1,
    "createdOn": "2008-04-14 03:15:52"
  },
  {
    "id": 96,
    "ratings": 4,
    "title": "Voluptatem fugit culpa dolorum sint.",
    "description": "Nostrum praesentium dolore consequuntur exercitationem rem. Nobis ut libero exercitationem hic suscipit ut repellendus. Eligendi sunt sed sit.",
    "productId": 6,
    "userId": 96,
    "report_abuse": 1,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 1,
    "createdOn": "2012-01-20 04:54:52"
  },
  {
    "id": 97,
    "ratings": 4,
    "title": "Quo cupiditate est sint sapiente qui fugit.",
    "description": "Non non iure nesciunt qui aut atque iste. Id dicta et est aperiam ipsa. In delectus iure repellendus earum architecto. Quisquam velit est fuga eum quos.",
    "productId": 7,
    "userId": 97,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1983-04-10 19:20:49"
  },
  {
    "id": 98,
    "ratings": 4,
    "title": "Totam delectus dolorem velit quis libero excepturi occaecati.",
    "description": "Qui in enim quam nulla. Assumenda velit quidem autem eos est qui. Ut veniam non dolores dolores repellendus doloribus. Ipsam et porro voluptas et occaecati reprehenderit cum.",
    "productId": 8,
    "userId": 98,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1983-07-06 03:25:27"
  },
  {
    "id": 99,
    "ratings": 1,
    "title": "Quia magni quos et sed non ad minima.",
    "description": "Aliquid voluptatibus incidunt qui sint. Ducimus qui odio saepe. Nam provident soluta sint.",
    "productId": 9,
    "userId": 99,
    "report_abuse": 0,
    "isProductProp1Good": 1,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "2001-12-25 11:46:32"
  },
  {
    "id": 100,
    "ratings": 1,
    "title": "Itaque voluptatum aspernatur et eum rerum.",
    "description": "Voluptas earum molestiae et error. Quos odio iste consequatur vel accusamus sit. Earum vero ratione pariatur nihil quos neque occaecati.",
    "productId": 10,
    "userId": 100,
    "report_abuse": 0,
    "isProductProp1Good": 0,
    "isProductProp2Good": 0,
    "isProductProp3Good": 0,
    "createdOn": "1990-06-21 10:53:04;"
  }
];